# Generated by Django 3.1.2 on 2020-10-04 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DeskShare', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SharedFiles',
        ),
    ]
