# Generated by Django 2.1 on 2020-11-16 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DeskShare', '0002_delete_sharedfiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_contents', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DeskShare.Upload')),
            ],
        ),
    ]
