# Generated by Django 2.1 on 2020-11-16 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DeskShare', '0003_sharefile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharefile',
            name='upload_contents',
        ),
        migrations.DeleteModel(
            name='ShareFile',
        ),
    ]
